### ISSUE TITLE
Hiba /events/:id/demonstrator végpontnál

### ISSUE THREAD

**Issue by zsambek** [bme-db-lab/szglab5-backend#30]
Hiba:

1. seed: `npm run cli:dev seed test.seed.json`
2. GET /events/1/demonstrator
3. ERROR:
```
Unhandled rejection SequelizeDatabaseError: operator does not exist: character varying = integer
    at Query.formatError (D:\DEVELOPMENT\labor-admin\szglab5-backend\node_modules\sequelize\lib\dialects\postgres\query.js:357:14)
    at Query.<anonymous> (D:\DEVELOPMENT\labor-admin\szglab5-backend\node_modules\sequelize\lib\dialects\postgres\query.js:88:19)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:188:7)
    at Query.handleError (D:\DEVELOPMENT\labor-admin\szglab5-backend\node_modules\pg\lib\query.js:143:8)

    at Connection.<anonymous> (D:\DEVELOPMENT\labor-admin\szglab5-backend\node_modules\pg\lib\client.js:180:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (D:\DEVELOPMENT\labor-admin\szglab5-backend\node_modules\pg\lib\connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TCP.onread (net.js:548:20)
```

**Comment by jmarton** [comment]
Kapcsolódik #31 (talán ismétlés?)
